
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgrlbuqxuahignpuwvfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncmxidXF4dWFoaWducHV3dmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzEyOTUsImV4cCI6MjA1NzM0NzI5NX0.aQPAAX60yawLZHvLIjOEEZqvTT0Pj6TrHXCtXXOlq-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Manually add typed method for our RPC functions
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    rpc<T = any>(
      fn: 'get_user_job_applications', 
      params: { user_id_param: string }
    ): Promise<{ data: string[]; error: any }>;
  }
}
